# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('royalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'franchise_brands',
            },
        ),
        migrations.CreateModel(
            name='Franchisee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('applicant', 'Applicant'), ('screening', 'Screening'), ('approved', 'Approved'), ('active', 'Active'), ('terminated', 'Terminated')], default='applicant', max_length=50)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('liquid_capital', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchisees', to='franchise.franchisebrand')),
            ],
            options={
                'db_table': 'franchise_franchisees',
            },
        ),
        migrations.CreateModel(
            name='FranchiseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('opening_date', models.DateField(null=True)),
                ('launch_status', models.CharField(choices=[('pipeline', 'Pipeline'), ('site_selection', 'Site Selection'), ('lease_negotiation', 'Lease Negotiation'), ('construction', 'Construction'), ('training', 'Training'), ('pre_open', 'Pre-Open'), ('open', 'Open')], default='pipeline', max_length=50)),
                ('target_open_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('franchisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='franchise.franchisee')),
            ],
            options={
                'db_table': 'franchise_locations',
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('percent_complete', models.IntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_phases', to='franchise.franchiselocation')),
            ],
            options={
                'db_table': 'franchise_construction_phases',
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=100.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=50)),
                ('findings', models.JSONField(default=list)),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='franchise.franchiselocation')),
            ],
            options={
                'db_table': 'franchise_compliance_scores',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='franchise.franchiselocation')),
            ],
            options={
                'db_table': 'franchise_milestones',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(default='video', max_length=50)),
                ('content_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('sequence', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='franchise.franchisebrand')),
            ],
            options={
                'db_table': 'franchise_training_modules',
            },
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.UUIDField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.franchiselocation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.trainingmodule')),
            ],
            options={
                'db_table': 'franchise_training_completions',
                'unique_together': {('employee_id', 'module')},
            },
        ),
    ]
