# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='unit', max_length=50)),
                ('target_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sourcing_products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(default='direct', max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sourcing_suppliers',
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('shipped', 'Shipped'), ('received', 'Received')], default='planned', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('expected_ship_date', models.DateField(null=True)),
                ('actual_ship_date', models.DateField(null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='sourcing.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.supplier')),
            ],
            options={
                'db_table': 'sourcing_production_runs',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('shipped_at', models.DateTimeField(null=True)),
                ('estimated_arrival', models.DateField(null=True)),
                ('arrived_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='in_transit', max_length=50)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sourcing.productionrun')),
            ],
            options={
                'db_table': 'sourcing_shipments',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcing.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('moq', models.IntegerField(null=True)),
                ('lead_time_days', models.IntegerField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sourcing.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sourcing.supplier')),
            ],
            options={
                'db_table': 'sourcing_quotes',
            },
        ),
    ]
