# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_chunks', models.JSONField(default=list)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfp_generated_responses',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='knowledge/')),
                ('content', models.TextField(blank=True)),
                ('doc_type', models.CharField(default='policy', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rfp_knowledge_documents',
            },
        ),
        migrations.CreateModel(
            name='RFPRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='rfps/')),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('generating', 'Generating'), ('review', 'Review'), ('approved', 'Approved'), ('exported', 'Exported')], default='uploaded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rfp_requests',
            },
        ),
        migrations.CreateModel(
            name='ComplianceGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('fedramp', 'FedRAMP'), ('pci_dss', 'PCI-DSS')], max_length=50)),
                ('issue', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gaps', to='rfp.generatedresponse')),
            ],
            options={
                'db_table': 'rfp_compliance_gaps',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding_id', models.CharField(blank=True, max_length=255)),
                ('sequence', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rfp.knowledgedocument')),
            ],
            options={
                'db_table': 'rfp_knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='RFPSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sequence', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rfp.rfprequest')),
            ],
            options={
                'db_table': 'rfp_sections',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='generatedresponse',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='rfp.rfpsection'),
        ),
    ]
