# Generated by Django 6.0.6 on 2026-06-09 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(null=True)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('before_state', models.JSONField(null=True)),
                ('after_state', models.JSONField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
