# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('project_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('completion_date', models.DateField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'construction_projects',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drawing_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('mep', 'MEP'), ('civil', 'Civil'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('fire_protection', 'Fire Protection')], max_length=100)),
                ('file', models.FileField(upload_to='drawings/')),
                ('revision', models.CharField(max_length=50)),
                ('revision_date', models.DateField(null=True)),
                ('uploaded_by_id', models.UUIDField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='construction.project')),
            ],
            options={
                'db_table': 'construction_drawings',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('crew_count', models.IntegerField(default=0)),
                ('progress_notes', models.TextField(blank=True)),
                ('issues', models.JSONField(default=list)),
                ('photos', models.JSONField(default=list)),
                ('submitted_by_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='construction.project')),
            ],
            options={
                'db_table': 'construction_daily_reports',
            },
        ),
        migrations.CreateModel(
            name='RevisionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('differences', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('new_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_analyses', to='construction.drawing')),
                ('old_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_analyses', to='construction.drawing')),
            ],
            options={
                'db_table': 'construction_revision_analyses',
            },
        ),
        migrations.CreateModel(
            name='TradePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('electrical', 'Electrical'), ('hvac', 'HVAC'), ('plumbing', 'Plumbing'), ('concrete', 'Concrete'), ('framing', 'Framing'), ('drywall', 'Drywall'), ('roofing', 'Roofing'), ('structural', 'Structural'), ('fire_protection', 'Fire Protection'), ('millwork', 'Millwork')], max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_packages', to='construction.project')),
            ],
            options={
                'db_table': 'construction_trade_packages',
            },
        ),
        migrations.CreateModel(
            name='PunchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=50)),
                ('due_date', models.DateField(null=True)),
                ('photos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_items', to='construction.project')),
                ('assigned_trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.tradepackage')),
            ],
            options={
                'db_table': 'construction_punch_items',
            },
        ),
        migrations.CreateModel(
            name='MaterialImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('quantity_delta', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('estimated_cost_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_impacts', to='construction.revisionanalysis')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.tradepackage')),
            ],
            options={
                'db_table': 'construction_material_impacts',
            },
        ),
    ]
