# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('route_date', models.DateField()),
                ('driver_id', models.UUIDField(null=True)),
                ('vehicle_id', models.UUIDField(null=True)),
                ('stops', models.JSONField(default=list)),
                ('total_distance_miles', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=50)),
                ('optimized', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'food_delivery_routes',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('certifications', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'food_farms',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(default='lb', max_length=50)),
                ('avg_shelf_life_days', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'food_produce',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'food_stores',
            },
        ),
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('quality_grade', models.CharField(default='A', max_length=10)),
                ('available_quantity', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='food.farm')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.produce')),
            ],
            options={
                'db_table': 'food_harvest_logs',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.FloatField()),
                ('quantity_delivered', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('delivered_at', models.DateTimeField(null=True)),
                ('signature_url', models.URLField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='food.deliveryroute')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.harvestlog')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.store')),
            ],
            options={
                'db_table': 'food_deliveries',
            },
        ),
    ]
