# Generated by Django 6.0.6 on 2026-06-09 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'domain_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('handler_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'event_subscriptions',
            },
        ),
    ]
