# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parcel_id', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('utility_provider', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solar_properties',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_type', models.CharField(choices=[('building', 'Building Permit'), ('electrical', 'Electrical Permit'), ('interconnection', 'Utility Interconnection'), ('net_metering', 'Net Metering Application')], max_length=50)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=50)),
                ('permit_number', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('documents', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='solar.property')),
            ],
            options={
                'db_table': 'solar_permits',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed'), ('reinspection', 'Re-inspection Required')], default='scheduled', max_length=50)),
                ('inspector_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='solar.property')),
            ],
            options={
                'db_table': 'solar_inspections',
            },
        ),
        migrations.CreateModel(
            name='RoofPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(default=dict)),
                ('area_sqft', models.FloatField(default=0)),
                ('azimuth', models.FloatField()),
                ('pitch', models.FloatField()),
                ('usable_area_sqft', models.FloatField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_planes', to='solar.property')),
            ],
            options={
                'db_table': 'solar_roof_planes',
            },
        ),
        migrations.CreateModel(
            name='SetbackValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=100)),
                ('required_ft', models.FloatField()),
                ('actual_ft', models.FloatField()),
                ('passed', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setback_validations', to='solar.property')),
            ],
            options={
                'db_table': 'solar_setback_validations',
            },
        ),
        migrations.CreateModel(
            name='SolarArray',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_model', models.CharField(blank=True, max_length=255)),
                ('panel_count', models.IntegerField()),
                ('system_kw', models.FloatField()),
                ('estimated_annual_kwh', models.FloatField(default=0)),
                ('tilt', models.FloatField(default=0)),
                ('azimuth', models.FloatField(default=180)),
                ('roof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrays', to='solar.roofplane')),
            ],
            options={
                'db_table': 'solar_arrays',
            },
        ),
    ]
