# Generated by Django 6.0.6 on 2026-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=100)),
                ('metadata', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_flags',
                'unique_together': {('organization_id', 'key')},
            },
        ),
    ]
