# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('property_type', models.CharField(default='apartment', max_length=100)),
                ('max_guests', models.IntegerField(default=2)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.FloatField(default=1)),
                ('wifi_password', models.CharField(blank=True, max_length=255)),
                ('door_code', models.CharField(blank=True, max_length=100)),
                ('check_in_instructions', models.TextField(blank=True)),
                ('house_rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hospitality_properties',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('vrbo', 'VRBO'), ('booking_com', 'Booking.com'), ('direct', 'Direct')], max_length=50)),
                ('platform_reservation_id', models.CharField(blank=True, max_length=255)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_count', models.IntegerField(default=1)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('nightly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hospitality.rentalproperty')),
            ],
            options={
                'db_table': 'hospitality_reservations',
            },
        ),
        migrations.CreateModel(
            name='GuestThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('platform', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hospitality.reservation')),
            ],
            options={
                'db_table': 'hospitality_guest_threads',
            },
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('cleaner_id', models.UUIDField(null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='scheduled', max_length=50)),
                ('checklist', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='hospitality.rentalproperty')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_jobs', to='hospitality.reservation')),
            ],
            options={
                'db_table': 'hospitality_cleaning_jobs',
            },
        ),
        migrations.CreateModel(
            name='SmartLockCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('lock_provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('created', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock_code', to='hospitality.reservation')),
            ],
            options={
                'db_table': 'hospitality_lock_codes',
            },
        ),
    ]
