# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('car', 'Car'), ('trailer', 'Trailer'), ('heavy_equipment', 'Heavy Equipment')], max_length=50)),
                ('odometer', models.IntegerField(default=0)),
                ('engine_hours', models.FloatField(default=0)),
                ('license_plate', models.CharField(blank=True, max_length=50)),
                ('assigned_driver_id', models.UUIDField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'fleet_vehicles',
            },
        ),
        migrations.CreateModel(
            name='InventoryPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=5)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'fleet_inventory_parts',
                'unique_together': {('organization_id', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('severity', models.CharField(default='info', max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_telemetry_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_failure', models.CharField(max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField()),
                ('predicted_days', models.IntegerField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_maintenance_predictions',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting Parts'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=50)),
                ('description', models.TextField()),
                ('assigned_mechanic_id', models.UUIDField(null=True)),
                ('parts_used', models.JSONField(default=list)),
                ('labor_hours', models.FloatField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('scheduled_date', models.DateField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'fleet_work_orders',
            },
        ),
    ]
