# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('accounting', 'Accounting'), ('crm', 'CRM'), ('gis', 'GIS'), ('email', 'Email'), ('sms', 'SMS'), ('storage', 'Storage'), ('scheduling', 'Scheduling'), ('erp', 'ERP'), ('iot', 'IoT / Telematics'), ('payments', 'Payments'), ('documents', 'Documents'), ('project_mgmt', 'Project Management'), ('lms', 'LMS')], max_length=100)),
                ('auth_type', models.CharField(choices=[('oauth2', 'OAuth2'), ('api_key', 'API Key'), ('basic', 'Basic Auth'), ('webhook', 'Webhook')], max_length=50)),
                ('logo_url', models.URLField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('supported_verticals', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='OrganizationIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('credentials', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'db_table': 'organization_integrations',
                'unique_together': {('organization_id', 'integration')},
            },
        ),
    ]
