# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('local', 'Local Model')], max_length=100, unique=True)),
                ('api_key_env_var', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'ai_providers',
            },
        ),
        migrations.CreateModel(
            name='ResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(max_length=64, unique=True)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'response_cache',
            },
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('source_type', models.CharField(max_length=100)),
                ('source_id', models.CharField(max_length=100)),
                ('chunk_text', models.TextField()),
                ('embedding_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vector_documents',
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('rfp_response', 'RFP Response Generation'), ('compliance_check', 'Compliance Check'), ('drawing_analysis', 'Drawing Analysis'), ('demand_forecast', 'Demand Forecast'), ('guest_message', 'Guest Message'), ('trade_impact', 'Trade Impact Analysis'), ('permit_extract', 'Permit Data Extraction'), ('maintenance_predict', 'Maintenance Prediction'), ('route_optimize', 'Route Optimization'), ('general', 'General')], max_length=100)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.FloatField(default=0.3)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiprompttemplate')),
            ],
            options={
                'db_table': 'ai_requests',
            },
        ),
    ]
